//
//  ImportData.swift
//  GroceryApp
//
//  Import data for common grocery items
//  This file can be manually updated to add/modify items and store assignments
//
//  Format: (name: String, category: String, store: String?)
//  - name: Item name
//  - category: Category name (must match existing categories)
//  - store: Store name (must match existing stores, or nil for no store)
//

import Foundation

struct ImportData {
    /// Common grocery items organized by category with optional store assignments
    /// Update this list to add new items or assign stores to existing items
    static let commonItems: [(name: String, category: String, store: String?)] = [
        // Produce
        ("Apples", "Produce", "Trader Joe's"),
        ("Apples", "Produce", "Sprouts"),
        ("Bananas", "Produce", "Trader Joe's"),
        ("Oranges", "Produce", "Trader Joe's"),
        ("Oranges", "Produce", "Sprouts"),
        ("Mandarins", "Produce", "Sprouts"),
        ("Mandarins", "Produce", "Trader Joe's"),
        ("Grapes", "Produce", "Sprouts"),
        ("Strawberries", "Produce", "Sprouts"),
        ("Strawberries", "Produce", "Trader Joe's"),
        ("Blueberries", "Produce", "Sprouts"),
        ("Blueberries", "Produce", "Trader Joe's"),
        ("Raspberries", "Produce", "Sprouts"),
        ("Blackberries", "Produce", "Sprouts"),
        ("Avocados", "Produce", "Sprouts"),
        ("Avocados", "Produce", "Trader Joe's"),
        ("Cantaloupe", "Produce", "Sprouts"),
        ("Watermelon", "Produce", "Sprouts"),
        ("Honeydew", "Produce", "Sprouts"),
        ("Lettuce", "Produce", "Sprouts"),
        ("Lettuce", "Produce", "Trader Joe's"),
        ("Spinach", "Produce", "Sprouts"),
        ("Spinach", "Produce", "Trader Joe's"),
        ("Tomatoes", "Produce", "Sprouts"),
        ("Tomatoes", "Produce", "Trader Joe's"),
        ("Carrots", "Produce", "Sprouts"),
        ("Carrots", "Produce", "Trader Joe's"),
        ("Cabbage", "Produce", "Sprouts"),
        ("Cabbage", "Produce", "Trader Joe's"),
        ("Cauliflower", "Produce", "Sprouts"),
        ("Cauliflower", "Produce", "Trader Joe's"),
        ("Asparagus", "Produce", "Sprouts"),
        ("Asparagus", "Produce", "Tradere Joe's"),
        ("Broccoli", "Produce", "Sprouts"),
        ("Broccoli", "Produce", "Trader Joe's"),
        ("Corn on the Cob", "Produce", "Sprouts"),
        ("Eggplant", "Produce", "Trader Joe's"),
        ("Summer Squash", "Produce", "Trader Joe's"),
        ("Spaghetti Squash", "Produce", "Trader Joe's"),
        ("Zucchini", "Produce", "Trader Joe's"),
        ("Pumpkin", "Produce", "Trader Joe's"),
        ("Turnips", "Produce", "Sprouts"),
        ("Kale", "Produce", "Sprouts"),
        ("Collard Greens", "Produce", "Sprouts"),
        ("Mustard Greens", "Produce", "Sprouts"),
        ("Turnips", "Produce", "Trader Joe's"),
        ("Radish", "Produce", "Trader Joe's"),
        ("Radish", "Produce", "Sprouts"),
        ("Red Beets", "Produce", "Trader Joe's"),
        ("Acorn Squash", "Produce", "Trader Joe's"),
        ("Brussel Sprouts", "Produce", "Sprouts"),
        ("Brussel Sprouts", "Produce", "Trader Joe's"),
        ("Onions", "Produce", "Sprouts"),
        ("Garlic", "Produce", "Sprouts"),
        ("Potatoes", "Produce", "Sprouts"),
        ("Potatoes", "Produce", "Trader Joe's"),
        ("Sweet Potatoes", "Produce", "Sprouts"),
        ("Sweet Potatoes", "Produce", "Trader Joe's"),
        ("Baby Bell Peppers", "Produce", "Sprouts"),
        ("Baby Bell Peppers", "Produce", "Trader Joe's"),
        ("Cucumbers", "Produce", "Sprouts"),
        ("Cucumbers", "Produce", "Trader Joe's"),
        ("Green Beans", "Produce", "Sprouts"),
        ("Green Beans", "Produce", "Trader Joe's"),
        ("Button Mushrooms", "Produce", "Sprouts"),
        ("Button Mushrooms", "Produce", "Trader Joe's"),
        ("Cremini Mushrooms", "Produce", "Sprouts"),
        ("Cremini Mushrooms", "Produce", "Trader Joe's"),
        ("Celery", "Produce", "Sprouts"),
        ("Celery", "Produce", "Trader Joe's"),
        ("Sugar Snap Peas", "Produce", "Sprouts"),
        ("Sugar Snap Peas", "Produce", "Trader Joe's"),
        ("Gai Lan", "Produce", "Ranch 99"),
        ("Baby Bok Choy", "Produce", "Ranch 99"),
        ("Napa Cabbage", "Produce", "Ranch 99"),
        ("Choy Dim", "Produce", "Ranch 99"),
        ("Snow Peas", "Produce", "Ranch 99"),
        ("Daikon Radish", "Produce", "Ranch 99"),
        ("Japanese Eggplant", "Produce", "Ranch 99"),
        ("Kombucha", "Produce", "Ranch 99"),
        ("Lotus Root", "Produce", "Ranch 99"),
        ("Ginger Root", "Produce", "Ranch 99"),
        ("Baby Oyster Mushrooms", "Produce", "Ranch 99"),
        ("Enoki Mushrooms", "Produce", "Ranch 99"),
        ("Wood Ear Mushrooms", "Produce", "Ranch 99"),
        ("Shiitake Mushrooms", "Produce", "Ranch 99"),
        ("Shimeji Mushrooms", "Produce", "Ranch 99"),
        ("Portobello Mushrooms", "Produce", "Monterey Market"),
        ("Porcini Mushrooms", "Produce", "Monterey Market"),
        ("Morel Mushrooms", "Produce", "Monterey Market"),
        ("Chanterelle Mushrooms", "Produce", "Monterey Market"),
        ("Maitake Mushrooms", "Produce", "Monterey Market"),

        // Dairy
        ("Whole Milk", "Dairy", "Sprouts"),
        ("Soy Milk", "Dairy", "Sprouts"),
        ("Oat Milk", "Dairy", "Trader Joe's"),
        ("Silken Tofu", "Dairy", "Ranch 99"),
        ("Eggs", "Dairy", "Costco"),
        ("Eggs", "Dairy", "Sprouts"),
        ("Eggs", "Dairy", "Trader Joe's"),
        ("Butter", "Dairy", "Sprouts"),
        ("Butter", "Dairy", "Trader Joe's"),
        ("Cheddar Cheese", "Dairy", "Trader Joe's"),
        ("Cheddar Cheese", "Dairy", "Sprouts"),
        ("Swiss Cheese", "Dairy", "Trader Joe's"),
        ("Swiss Cheese", "Dairy", "Sprouts"),
        ("Meunster Cheese", "Dairy", "Trader Joe's"),
        ("Meunster Cheese", "Dairy", "Sprouts"),
        ("Blue Cheese", "Dairy", "Trader Joe's"),
        ("Artisan Cheese", "Dairy", "Trader Joe's"),
        ("Cream Cheese", "Dairy", "Trader Joe's"),
        ("Cottage Cheese", "Dairy", "Trader Joe's"),
        ("Yogurt", "Dairy", "Trader Joe's"),
        ("Yogurt", "Dairy", "Sprouts"),
        ("Heavy Cream", "Dairy", "Trader Joe's"),
        ("Sour Cream", "Dairy", "Trader Joe's"),
        ("Half and Half", "Dairy", "Trader Joe's"),
        
        // Meat & Seafood
        ("Chicken Breast", "Meat & Seafood", "Costco"),
        ("Chicken Thighs", "Meat & Seafood", "Costco"),
        ("Chicken Legs", "Meat & Seafood", "Costco"),
        ("Ground Beef", "Meat & Seafood", "Sprouts"),
        ("Beef Tri Tip Steak", "Meat & Seafood", "Sprouts"),
        ("Wild caught Salmon", "Meat & Seafood", "Costco"),
        ("Wild caught Shrimp", "Meat & Seafood", "Costco"),
        ("Wild caught Pacific Cod", "Meat & Seafood", "Costco"),
        ("Dungeness Crab", "Meat & Seafood", "Ranch 99"),
        ("Sliced Pork ", "Meat & Seafood", "Ranch 99"),
        ("Sliced Beef Short Ribs", "Meat & Seafood", "Ranch 99"),
        ("P.E.I. Mussels", "Meat & Seafood", "Andronico's"),
        ("Pork Chops", "Meat & Seafood", "Sprouts"),
        ("Pork Ribs", "Meat & Seafood", "Sprouts"),
        ("Pork Sausage", "Meat & Seafood", "Trader Joe's"),
        ("Pork Bacon", "Meat & Seafood", "Costco"),
        ("Ground Turkey", "Meat & Seafood", "Sprouts"),
        
        // Deli
        ("Soup", "Deli", "Andronico's"),
        ("Chowder", "Deli", "Andronico's"),
        ("Bisque", "Deli", "Andronico's"),
        ("Jambalaya", "Deli", "Andronico's"),
        ("Artisan Sandwich", "Deli", "Andronico's"),
        ("Pizza", "Deli", "Andronico's"),
        ("Sushi", "Deli", "Sprouts"),
        ("Kimchi", "Deli", "Ranch 99"),
        ("Udon Noodles", "Deli", "Ranch 99"),
        ("Ramen Noodles", "Deli", "Ranch 99"),
        ("Sukiyaki Noodles", "Deli", "Ranch 99"),
        
        // Bakery
        ("Sliced Bread", "Bakery", "Sprouts"),
        ("Cranberry Walnut Bread", "Bakery", "Berkeley Bowl"),
        ("Olive Bread", "Bakery", "Berkeley Bowl"),
        ("French Bread", "Bakery", "Trader Joe's"),
        ("Sourdough", "Bakery", "Trader Joe's"),
        ("Muffins", "Bakery", "Sprouts"),
        ("Danish", "Bakery", "Sprouts"),
        ("Cookies", "Bakery", "Sprouts"),
        ("Tortillas", "Bakery", "Target"),
        
        // Pantry Staples
        ("Short grain Rice", "Pantry Staples", "Ranch 99"),
        ("Long grain Rice", "Pantry Staples", "Ranch 99"),
        ("Spaghetti Pasta", "Pantry Staples", "Target"),
        ("Angel Hair Pasta", "Pantry Staples", "Target"),
        ("Macaroni Pasta", "Pantry Staples", "Target"),
        ("White Sugar", "Pantry Staples", "Target"),
        ("Olive Oil", "Pantry Staples", "Target"),
        ("Vegetable Oil", "Pantry Staples", "Target"),
        ("Vinegar", "Pantry Staples", "Target"),
        ("Peanut Butter", "Pantry Staples", "Sprouts"),
        ("Seed Butter", "Pantry Staples", "Target"),
        
        // Canned Goods
        ("Canned Diced Tomatoes", "Canned Goods", "Trader Joe's"),
        ("Canned Tomato Paste", "Canned Goods", "Trader Joe's"),
        ("Jarred Tomato Sauce", "Canned Goods", "Trader Joe's"),
        ("Jarred Bechtel Sauce", "Canned Goods", "Trader Joe's"),
        ("Jarred Alfredo Sauce", "Canned Goods", "Trader Joe's"),
        ("Jarred Clam Sauce", "Canned Goods", "Trader Joe's"),
        ("Canned Navy Beans", "Canned Goods", "Whole Foods"),
        ("Canned Kidney Beans", "Canned Goods", "Whole Foods"),
        ("Canned Pinto Beans", "Canned Goods", "Whole Foods"),
        ("Canned Black Beans", "Canned Goods", "Whole Foods"),
        ("Canned Garbanzo Beans", "Canned Goods", "Whole Foods"),
        ("Canned Coconut Milk", "Canned Goods", "Ranch 99"),
        ("Packaged Red Curry", "Canned Goods", "Ranch 99"),
        ("Packaged Green Curry", "Canned Goods", "Ranch 99"),
        ("Packaged Yellow Curry", "Canned Goods", "Ranch 99"),
        ("Jarred Bamboo", "Canned Goods", "Ranch 99"),
        ("Jarred Fried Gluten", "Canned Goods", "Ranch 99"),
        ("Jarred Pickled Radish", "Canned Goods", "Ranch 99"),
        ("Canned Salmon", "Canned Goods", "Costco"),
        ("Canned Tuna", "Canned Goods", "Costco"),
        ("Packaged Chicken Broth", "Canned Goods", "Trader Joe's"),
        ("Packaged Beef Broth", "Canned Goods", "Trader Joe's"),
        ("Packaged Vegetable Broth", "Canned Goods", "Trader Joe's"),
        ("Canned Peas", "Canned Goods", "Target"),
        ("Canned Corn", "Canned Goods", "Target"),
        ("Canned Peaches", "Canned Goods", "Target"),
        ("Canned Pears", "Canned Goods", "Target"),
        
        // Beverages
        ("Bottled Water", "Beverages", "Target"),
        ("Canned Flavored Water", "Beverages", "Target"),
        ("Ground Coffee", "Beverages", "Target"),
        ("Ginger Tea", "Beverages", "Ranch 99"),
        ("Green Tea", "Beverages", "Ranch 99"),
        ("Barley Tea", "Beverages", "Ranch 99"),
        ("Canned Beer", "Beverages", "Target"),
        ("Bottled Wine", "Beverages", "Target"),
        
        // Snacks
        ("Potato Chips", "Snacks", "Andronico's"),
        ("Nacho Chips", "Snacks", "Trader Joe's"),
        ("Saltine Crackers", "Snacks", "Andronico's"),
        ("Round Crackers", "Snacks", "Trader Joe's"),
        ("Peanuts", "Snacks", "Trader Joe's"),
        ("Cashews", "Snacks", "Trader Joe's"),
        ("Almonds", "Snacks", "Trader Joe's"),
        ("Pistachios", "Snacks", "Trader Joe's"),
        ("Popcorn", "Snacks", "Target"),
        ("Seaweed", "Snacks", "Trader Joe's"),
        ("Jerky", "Snacks", "Target"),
        ("Boxed Raisins", "Snacks", "Target"),
        ("Granola Bars", "Snacks", "Target"),
        ("Fruit Bars", "Snacks", "Target"),
        
        // Condiments & Spices
        ("Ketchup", "Condiments & Spices", "Target"),
        ("Mustard", "Condiments & Spices", "Target"),
        ("Relish", "Condiments & Spices", "Target"),
        ("Mayonnaise", "Condiments & Spices", "Target"),
        ("Soy Sauce", "Condiments & Spices", "Ranch 99"),
        ("Dumpling Sauce", "Condiments & Spices", "Ranch 99"),
        ("Hoison Sauce", "Condiments & Spices", "Ranch 99"),
        ("Stir Fry Sauce", "Condiments & Spices", "Ranch 99"),
        ("Plum Sauce", "Condiments & Spices", "Ranch 99"),
        ("Korean BBQ Sauce", "Condiments & Spices", "Ranch 99"),
        ("Rice Vinegar", "Condiments & Spices", "Ranch 99"),
        ("Mirin Sauce", "Condiments & Spices", "Ranch 99"),
        ("Salt", "Condiments & Spices", "Target"),
        ("Pepper", "Condiments & Spices", "Target"),
        ("Oregano", "Condiments & Spices", "Target"),
        ("Basil", "Condiments & Spices", "Target"),
        ("Parsley", "Condiments & Spices", "Target"),
        ("Garlic Powder", "Condiments & Spices", "Target"),
        ("Onion Powder", "Condiments & Spices", "Target"),
        ("Paprika", "Condiments & Spices", "Target"),
        ("Rosemary", "Condiments & Spices", "Target"),
        ("Thyme", "Condiments & Spices", "Target"),
        ("Cumin", "Condiments & Spices", "Target"),
        ("Curry", "Condiments & Spices", "Target"),
        
        // Breakfast Items
        ("Cold Cereal", "Breakfast Items", "Trader Joe's"),
        ("Oatmeal", "Breakfast Items", "Target"),
        ("Quinoa", "Breakfast Items", "Target"),
        ("Pancake Mix", "Breakfast Items", "Target"),
        ("Maple Syrup", "Breakfast Items", "Target"),
        ("Wild Honey", "Breakfast Items", "Target"),
        ("Fruit Jam", "Breakfast Items", "Target"),
        ("Fruit Jelly", "Breakfast Items", "Target"),
        ("Fruit Marmalade", "Breakfast Items", "Target"),
        
        // Baking Supplies
        ("Baking Soda", "Baking Supplies", "Target"),
        ("Baking Powder", "Baking Supplies", "Target"),
        ("Vanilla Extract", "Baking Supplies", "Target"),
        ("Chocolate Chips", "Baking Supplies", "Target"),
        ("Brown Sugar", "Baking Supplies", "Target"),
        ("Powdered Sugar", "Baking Supplies", "Target"),
        ("Unbleached Flour", "Pantry Staples", "Target"),
        
        // Frozen
        ("Frozen Peas", "Frozen", "Sprouts"),
        ("Frozen Corn", "Frozen", "Sprouts"),
        ("Frozen Fruit Popsicles", "Frozen", "Sprouts"),
        ("Ice Cream", "Frozen", "Andronico's"),
        ("Frozen Pizza Rolls", "Frozen", "Andronico's"),
        ("Frozen Tater Tots", "Frozen", "Andronico's"),
        ("Frozen Chicken Pot Pies", "Frozen", "Andronico's"),
    ]
}
